### ISSUE TITLE
Flash Player Projector is missing on Flathub.org

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/com.adobe.Flash-Player-Projector#2]
The Flash Player Projector [page](https://flathub.org/apps/details/com.adobe.Flash-Player-Projector) is missing on the Flathub website and the Flatpak is also missing in GNOME Software. It looks like that there is some issue with the AppStream metadata.

**Comment by hadess** [comment]
I've fixed the screenshots not being the right size in commit 9ce1088d84279942d1569c190e3c42b1943883f3 though I don't understand why it would bail because of this. We have no visibility into the automated process to getting those packages online.

Maybe @jgarciao has an idea...

**Comment by hadess** [comment]
https://flathub.org/apps/details/org.freedesktop.Piper has the same problem, reported at:
https://github.com/flathub/org.freedesktop.Piper/issues/1

**Comment by jgarciao** [comment]
When an application is added to Flathub following the process described in the [app submission page](https://github.com/flathub/flathub/wiki/App-Submission) the Flathub service continuously builds the app and distributes it on every commit to the repository of the app.

In this process a file called _appstream.xml_ in the repository  is updated adding an entry for the new app. This is the file that the flathub.org web application reads to get the information about the applications in the repository.

If your app is not listed/updated in flathub.org you can follow this steps:
- Configure flatpak in your computer and add the flathub repo
- Update the appstream information with this command: `flatpak update --appstream`
- Unzip this file in your computer: /var/lib/flatpak/appstream/flathub/x86_64/active/appstream.xml.gz
-  Open it with a text editor
 - Make sure your app is listed and the entry has the required minimal fields:
   - id
   - name
   - summary
   - description
   - icon

In the case of com.adobe.Flash-Player-Projector the `<icon>` tag seems to be missing. That's why it's not listed in flathub.org

[This is the code](https://github.com/flathub/linux-store-backend/blob/fa54b23032bab3a952f9e7163e6d8b360e8a426a/src/main/java/org/flathub/api/service/UpdateServiceImpl.java#L275) of the web backend that reads the information in the appstream file

**Comment by hadess** [comment]
> In the case of com.adobe.Flash-Player-Projector the <icon> tag seems to be missing. That's why it's not listed in flathub.org

This is a bug in the backend, it doesn't know how to handle scalable icons as the only icon.

**Comment by LeandroStanger** [comment]
@hadess Did not work
![captura de tela de 2018-09-07 19-53-55](https://user-images.githubusercontent.com/26097419/45295610-b1462c80-b4d5-11e8-8046-77eecfc4d186.png)

**Comment by hadess** [comment]
> @hadess Did not work

Maybe wait longer than a few minutes?

**Comment by jgarciao** [comment]
I believe it's not working because you didn't provide a 64x64 icon. It's kind of documented [in the app requirements page](https://github.com/flathub/flathub/wiki/App-Requirements), but I understand that it should be more clear that is not working well with SVG

_Applications must provide application icons in at least 64×64px and 128×128px sizes. Application icons should either be included as scalable SVGs or high-resolution PNGs._

**Comment by hadess** [comment]
> Shouldn’t the build process just fail if it doesn’t pass the strict AppData requirements?

Completely agree there. The process of getting applications onto the website after it's been picked up by the bot is a complete black box, which is highly frustrating.

**Comment by jgarciao** [comment]
>Shouldn’t the build process just fail if it doesn’t pass the strict AppData requirements?

I also agree. I just added a check in the website-backend to avoid showing half-informed apps in the website. Before that we had apps without icons, descriptions and once even without name

**Comment by hadess** [comment]
I'm at a loss. The latest appstream data from the flathub repo doesn't make any mentions of the icons, despite them having been added to the built application, and the application getting rebuilt.

**Comment by jgarciao** [comment]
In gimp they had problems too with the icon tag not appearing. I think
@jehan and @hugsie found the solution

I hope it helps you

https://github.com/flathub/org.gimp.GIMP/issues/8



El dt., 11 de set. 2018, 14:14, hadess <notifications@github.com> va
escriure:

**Comment by hadess** [comment]
>  10   <launchable type="desktop-id">com.adobe.Flash-Player-Projector.desktop/</launchable>•

Spot the mistake.

This makes it throw an error:
https://github.com/hughsie/appstream-glib/pull/262

**Comment by hadess** [comment]
```
$ appstream-compose --verbose --prefix=_build/files/ --output-dir=out/ com.adobe.Flash-Player-Projector
WARNING: Metadata origin not set, using 'example'
Processing application com.adobe.Flash-Player-Projector
(appstream-compose:10318): As-DEBUG: 18:11:11.848: looking for appdata path '_build/files/share/appdata/com.adobe.Flash-Player-Projector.appdata.xml'
Invalid desktop filename: com.adobe.Flash-Player-Projector.desktop/
```
